name = "Pkg3"
repo = "https://github.com/StefanKarpinski/Pkg3.jl.git"
keywords = ["package", "management"]
license = "MIT"
authors = "Stefan Karpinski <stefan@karpinski.org>"
desc = "The next-generation Julia package manager."
